/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing;


import javax.swing.*;

public class Main extends JFrame {
    
  
 private boolean estConnecte = false;
    
    public void setEstConnecte(boolean value) {
        this.estConnecte = value;
        }
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
       jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        if (evt.getClickCount() == 1) { // Un seul clic
            jMenu4MouseClicked(evt);
        }
    }
});
       jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        if (evt.getClickCount() == 1) { // Un seul clic
            jMenu2MouseClicked(evt);
        }
    }
});
       jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        if (evt.getClickCount() == 1) { // Un seul clic
            jMenu3MouseClicked(evt);
        }
    }
});

       jMenu2.setEnabled(false); // Abonnés
    jMenu3.setEnabled(false); // Abonnements
    jMenu4.setEnabled(false); // Paiements
    
    
    
    AuthentificationFrame accueil = new AuthentificationFrame();
    desktopPane.add(accueil);
    accueil.setVisible(true);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuaccueil = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(51, 0, 51));

        jMenuBar1.setToolTipText("");

        menuaccueil.setText("Authentification");
        menuaccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuaccueilActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuaccueil);

        jMenu2.setText("Abonnés");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText(" Abonnements");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Paiements");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Help");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuaccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuaccueilActionPerformed
    
             javax.swing.JOptionPane.showMessageDialog(this, "Clic détecté !"); // Message visible
    
    AuthentificationFrame Authentification = new AuthentificationFrame();
    desktopPane.add(Authentification);
    Authentification.setSize(600, 500);
    Authentification.setLocation(100, 100);
    Authentification.setVisible(true);
    try {
        Authentification.setSelected(true);
        Authentification.toFront();
    } catch (Exception e) {}

             // TODO add your handling code here:
    }//GEN-LAST:event_menuaccueilActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
if (!estConnecte) {
        JOptionPane.showMessageDialog(this, "Veuillez d'abord vous connecter !");
        return;
    }    
    PaiementFrame pf = new PaiementFrame();
    desktopPane.add(pf);
    pf.setSize(900, 700);
    pf.setLocation(50, 50);
    pf.setVisible(true);
    
    try {
        pf.setSelected(true);
        pf.toFront();
    } catch (Exception e) {}       
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
 if (!estConnecte) {
        JOptionPane.showMessageDialog(this, "Veuillez d'abord vous connecter !");
        return;
    }
        for (javax.swing.JInternalFrame frame : desktopPane.getAllFrames()) {
        if (frame instanceof AbonneFrame) {
            try {
                frame.setSelected(true);
                frame.toFront();
                return; 
            } catch (Exception e) {}
        }
    }
    
    // Créer une nouvelle instance
    AbonneFrame abonne = new AbonneFrame();
    desktopPane.add(abonne);
    abonne.setSize(900, 700);
    abonne.setLocation(50, 50);
    abonne.setVisible(true);
    
    try {
        abonne.setSelected(true);
        abonne.toFront();
    } catch (Exception e) {}        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
if (!estConnecte) {
        JOptionPane.showMessageDialog(this, "Veuillez d'abord vous connecter !");
        return;
    }
        for (javax.swing.JInternalFrame frame : desktopPane.getAllFrames()) {
        if (frame instanceof AbonnementFrame) {
            try {
                frame.setSelected(true);
                frame.toFront();
                return; // Déjà ouvert, on sort
            } catch (Exception e) {}
        }
    }
    
    // Créer une nouvelle instance
    AbonnementFrame abonnement = new AbonnementFrame();
    desktopPane.add(abonnement);
    abonnement.setSize(900, 700);
    abonnement.setLocation(50, 50);
    abonnement.setVisible(true);
    
    // Mettre au premier plan
    try {
        abonnement.setSelected(true);
        abonnement.toFront();
    } catch (Exception e) {}
    }//GEN-LAST:event_jMenu3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuaccueil;
    // End of variables declaration//GEN-END:variables
}
